name: Build and Deploy

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: |
          pwd
          ls
          echo -n "" > vite.config.js
          cat <<EOF > vite.config.js
          import { fileURLToPath, URL } from 'node:url';
          import { defineConfig } from 'vite';
          import vue from '@vitejs/plugin-vue';
          export default defineConfig({
          plugins: [vue()],
          resolve: {
          alias: {
          '@': fileURLToPath(new URL('', import.meta.url))
          }
          },
          })
          EOF
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist